# Generated by Django 3.2.2 on 2024-10-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_auto_20241002_0044'),
        ('e_commerce', '0003_auto_20241002_0055'),
    ]

    operations = [
    ]
